"""Small Changes

Revision ID: 3ef6d08cfc9c
Revises: f70ae433d79c
Create Date: 2024-04-29 18:59:58.055752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef6d08cfc9c'
down_revision = 'f70ae433d79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
