"""New perms

Revision ID: 47a647a632ce
Revises: bfca4f3a7486
Create Date: 2024-04-29 23:09:24.209662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a647a632ce'
down_revision = 'bfca4f3a7486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_verify_comics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_publish_comics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_verify_chapters', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_publish_chapters', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_column('can_publish_chapters')
        batch_op.drop_column('can_verify_chapters')
        batch_op.drop_column('can_publish_comics')
        batch_op.drop_column('can_verify_comics')

    # ### end Alembic commands ###
