"""Some permissions are removed due to security reasons.

Revision ID: 96c513f5b8d5
Revises: 4801eed725e7
Create Date: 2024-05-01 05:56:44.363354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96c513f5b8d5'
down_revision = '4801eed725e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_column('can_delete_users')
        batch_op.drop_column('can_edit_users')
        batch_op.drop_column('can_create_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_users', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_edit_users', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_delete_users', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
